"""add deletedAt column

Revision ID: 101050cf5f2b
Revises: df25095d816a
Create Date: 2021-10-16 20:10:50.552683

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '101050cf5f2b'
down_revision = 'df25095d816a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletedAt')
    # ### end Alembic commands ###
