"""one more migration

Revision ID: 721596a9a391
Revises: 101050cf5f2b
Create Date: 2021-10-19 13:10:02.730143

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '721596a9a391'
down_revision = '101050cf5f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olympiads', sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('olympiads', 'deletedAt')
    # ### end Alembic commands ###
